Feature/UI account settings
alinauman02/instagram-clone pull request #13
Opened 2022-11-04 10:16 UTC by ejaz-hussain-1050

Creating UI for account settings

2022-11-08 04:51 UTC, alinauman02 requested changes

2022-11-08 04:51 UTC, alinauman02 commented on frontend/src/components/settings/EditPassword.css
> +.edit-submit-google:hover {
This selector is not used in the corresponding component. Why is this here?

2022-11-08 04:51 UTC, alinauman02 commented on frontend/src/components/settings/EditPassword.tsx
> +  const onChange = (e: React.FormEvent<HTMLInputElement>) => {
Use `event` instead of `e`. `e` can be confusing - it could also be an error.

2022-11-08 04:51 UTC, alinauman02 commented on frontend/src/components/settings/EditPassword.tsx
> +          <span className="edit-password-label">Password</span>
`span` is not the element that should be used here. There is a more appropriate element that can be "connected" with an input field. Find and use that.

2022-11-08 04:51 UTC, alinauman02 commented on frontend/src/components/settings/EditPassword.tsx
> +        </div>
This markup with a `div` wrapping a `span` and `Input` component looks repetitive... could it be extracted into a reusable component?

2022-11-08 04:51 UTC, alinauman02 commented on frontend/src/components/settings/Input.tsx
> +  type: 'string' | 'email' | 'password' | 'number' | 'textarea';
Is `'textarea'` a valid `type` for the `input` element?

2022-11-09 06:04 UTC, ZunairaT approved these changes, later dismissed

2022-11-09 06:04 UTC, ZunairaT commented on frontend/src/components/settings/EditPhoto.css
> +}
good usage of px em and % in this file in appropriate place :+1: goodjob

2022-11-09 06:39 UTC, alinauman02 commented
Clicking on the labels on the Edit Profile/Change Password pages does not bring focus to the corresponding input fields. Fix this.

2022-11-10 05:39 UTC, alinauman02 approved these changes

2022-11-10 06:03 UTC, ZunairaT approved these changes

2022-11-10 06:25 UTC, merged