Feature/authentication and authorization
alinauman02/instagram-clone pull request #20
Opened 2022-11-25 06:48 UTC by ejaz-hussain-1050

Authentication and authorization for getting and updating profile

2022-11-29 05:05 UTC, alinauman02 requested changes
Left a few comments. One more issue that I experienced: I cannot view a profile without being logged in. This is not what happens on Instagram.

2022-11-29 05:05 UTC, alinauman02 commented on backend/functions/src/middleware/can-edit-profile.ts
> +  } else next(new Error("'Authorization Error'"));
Remove the console log here and make the error message more descriptive

2022-11-29 05:05 UTC, alinauman02 commented on backend/functions/src/middleware/validate-id-token.ts
> +  } else next(new Error("'User not authenticated'"));
Rewrite this using `async`/`await` with `try`/`catch` block. Also use the `RequestHandler` type annotation on the function. Also, make the error message here more descriptive.

2022-11-29 05:05 UTC, alinauman02 commented on frontend/src/App.tsx
> +          {useAppSelector(selectUserId) && (
Can this repetition be removed?

2022-11-29 05:05 UTC, alinauman02 commented on frontend/src/components/Profile/Profile.tsx
> +  let username = useAppSelector(selectUserUsername);
Why do we need this?

2022-11-29 05:05 UTC, alinauman02 commented on frontend/src/components/settings/EditProfile/EditProfile.tsx
> +      navigate('/profile/5hsXfkYWNLyO9z0PTjQUVUgbJPyB');
Do not navigate away on editing profile.

2022-11-29 05:05 UTC, alinauman02 commented on frontend/src/components/ui/Header/Navbar/AccountOptions/AccountOptions.tsx
> +      dispatch(setAuthState({ id: '', token: '' }));
Also reset the username here.

2022-11-29 05:05 UTC, alinauman02 commented on frontend/src/store/slices/auth-slice.ts
> +export const selectUserUsername = (state: RootState) => state.auth.token;
`selectUserUsername`? Also, why is it returning the token?

2022-11-30 05:08 UTC, alinauman02 requested changes

2022-11-30 05:08 UTC, alinauman02 commented on backend/functions/src/@types/express/index.d.ts
> +    user: DecodedIdToken;
I think this should be an optional property, as it is only added when the authentication middleware is ran. If this marked as a required property, TypeScript will not tell us that is may be undefined.

2022-11-30 05:08 UTC, alinauman02 commented on backend/functions/src/api/resources/auth/auth.service.ts
> +  const res=await auth.createUser({ email, password });
`res` is typically used for `response`. Use a better name here.

2022-11-30 05:08 UTC, alinauman02 commented on backend/functions/src/api/resources/user-profile/user-profile.controller.ts
>  export const UpdateUserProfile: RequestHandler = async (req, res, next) => {
PascalCase?

2022-11-30 05:08 UTC, alinauman02 commented on backend/functions/src/middleware/can-edit-profile.ts
> +    } else throw new Error("'Authorization Error'");
You dont need the single quotes inside the double ones.

I think the error message should be more clear.

2022-11-30 05:08 UTC, alinauman02 commented on backend/functions/src/middleware/validate-id-token.ts
> +    } else throw new Error("'Authentication error! Token not found'");
Again, redundant `''` inside the double quotes.

2022-11-30 05:08 UTC, alinauman02 commented on frontend/src/components/Profile/Profile.tsx
> +  let username = useAppSelector(selectUserUsername);
@ejaz-hussain-1050 You marked this as resolved, but I see no response. Why do you need to read the username from the Redux store?

2022-11-30 05:08 UTC, alinauman02 commented on frontend/src/components/ui/Header/Navbar/AccountOptions/AccountOptions.tsx
> +          <Link className="list-link flex-box" to={'/' + username}>
Could use a template literal string (with back-ticks `` and ${}) instead of string concatenation.

Template literal strings are always preferred.

2022-11-30 05:08 UTC, alinauman02 commented on frontend/src/store/slices/auth-slice.ts
> +export const selectUserUsername = (state: RootState) => state.auth.username;
Change this to `selectUsername`

2022-11-30 05:11 UTC, alinauman02 commented
I still cannot see a user's profile if I am not logged in. Also, when I am not logged in OR I am viewing another user's profile, I should not see the edit profile buttons.

Also fix the alignment of these buttons.

2022-12-02 09:24 UTC, alinauman02 approved these changes

2022-12-02 09:55 UTC, ZunairaT approved these changes

2022-12-02 09:55 UTC, ZunairaT commented on backend/functions/src/api/resources/user-profile/user-profile.controller.ts
> +    // if (await checkEmail(userProfile.email)) throw new Error('Email already exists');
remove unused code

2022-12-02 10:00 UTC, ZunairaT approved these changes

2022-12-05 06:06 UTC, merged